language: node_js
node_js:
  - '0.11'
after_success:
  - openssl aes-256-cbc -K $encrypted_2f7ac37d66dd_key -iv $encrypted_2f7ac37d66dd_iv
    -in deploy_key.enc -out deploy_key -d
  - ssh-add deploy_key
  - git remote add deploy root@104.236.191.162:/var/www
  - git push deploy
