language: node_js
node_js:
  - '0.11'
after_success:
  - openssl aes-256-cbc -K $encrypted_2f7ac37d66dd_key -iv $encrypted_2f7ac37d66dd_iv
    -in deploy_key.enc -out deploy_key -d
  - chmod 400 deploy_key
  - eval `ssh-agent`
  - ssh-add deploy_key
  - echo 'ssh -o StrictHostKeyChecking=no $*' > ssh
  - chmod +x ssh
  - export GIT_SSH='./ssh'
  - git remote add deploy deploy@104.236.191.162:/home/git
  - '[ "${TRAVIS_BRANCH}" = "master" ] && git push deploy master'
